/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransportadorasRouteImport } from './routes/transportadoras'
import { Route as RepresentadasRouteImport } from './routes/representadas'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RepresentadasIndexRouteImport } from './routes/representadas.index'
import { Route as ClientesIndexRouteImport } from './routes/clientes.index'
import { Route as RepresentadasNovoRouteImport } from './routes/representadas.novo'
import { Route as ClientesNovoRouteImport } from './routes/clientes.novo'
import { Route as RepresentadasIdIndexRouteImport } from './routes/representadas.$id.index'
import { Route as ClientesIdIndexRouteImport } from './routes/clientes.$id.index'
import { Route as RepresentadasIdEditarRouteImport } from './routes/representadas.$id.editar'
import { Route as ClientesIdEditarRouteImport } from './routes/clientes.$id.editar'

const TransportadorasRoute = TransportadorasRouteImport.update({
  id: '/transportadoras',
  path: '/transportadoras',
  getParentRoute: () => rootRouteImport,
} as any)
const RepresentadasRoute = RepresentadasRouteImport.update({
  id: '/representadas',
  path: '/representadas',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RepresentadasIndexRoute = RepresentadasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RepresentadasRoute,
} as any)
const ClientesIndexRoute = ClientesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientesRoute,
} as any)
const RepresentadasNovoRoute = RepresentadasNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => RepresentadasRoute,
} as any)
const ClientesNovoRoute = ClientesNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => ClientesRoute,
} as any)
const RepresentadasIdIndexRoute = RepresentadasIdIndexRouteImport.update({
  id: '/$id/',
  path: '/$id/',
  getParentRoute: () => RepresentadasRoute,
} as any)
const ClientesIdIndexRoute = ClientesIdIndexRouteImport.update({
  id: '/$id/',
  path: '/$id/',
  getParentRoute: () => ClientesRoute,
} as any)
const RepresentadasIdEditarRoute = RepresentadasIdEditarRouteImport.update({
  id: '/$id/editar',
  path: '/$id/editar',
  getParentRoute: () => RepresentadasRoute,
} as any)
const ClientesIdEditarRoute = ClientesIdEditarRouteImport.update({
  id: '/$id/editar',
  path: '/$id/editar',
  getParentRoute: () => ClientesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRouteWithChildren
  '/representadas': typeof RepresentadasRouteWithChildren
  '/transportadoras': typeof TransportadorasRoute
  '/clientes/novo': typeof ClientesNovoRoute
  '/representadas/novo': typeof RepresentadasNovoRoute
  '/clientes/': typeof ClientesIndexRoute
  '/representadas/': typeof RepresentadasIndexRoute
  '/clientes/$id/editar': typeof ClientesIdEditarRoute
  '/representadas/$id/editar': typeof RepresentadasIdEditarRoute
  '/clientes/$id/': typeof ClientesIdIndexRoute
  '/representadas/$id/': typeof RepresentadasIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/transportadoras': typeof TransportadorasRoute
  '/clientes/novo': typeof ClientesNovoRoute
  '/representadas/novo': typeof RepresentadasNovoRoute
  '/clientes': typeof ClientesIndexRoute
  '/representadas': typeof RepresentadasIndexRoute
  '/clientes/$id/editar': typeof ClientesIdEditarRoute
  '/representadas/$id/editar': typeof RepresentadasIdEditarRoute
  '/clientes/$id': typeof ClientesIdIndexRoute
  '/representadas/$id': typeof RepresentadasIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRouteWithChildren
  '/representadas': typeof RepresentadasRouteWithChildren
  '/transportadoras': typeof TransportadorasRoute
  '/clientes/novo': typeof ClientesNovoRoute
  '/representadas/novo': typeof RepresentadasNovoRoute
  '/clientes/': typeof ClientesIndexRoute
  '/representadas/': typeof RepresentadasIndexRoute
  '/clientes/$id/editar': typeof ClientesIdEditarRoute
  '/representadas/$id/editar': typeof RepresentadasIdEditarRoute
  '/clientes/$id/': typeof ClientesIdIndexRoute
  '/representadas/$id/': typeof RepresentadasIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clientes'
    | '/representadas'
    | '/transportadoras'
    | '/clientes/novo'
    | '/representadas/novo'
    | '/clientes/'
    | '/representadas/'
    | '/clientes/$id/editar'
    | '/representadas/$id/editar'
    | '/clientes/$id/'
    | '/representadas/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/transportadoras'
    | '/clientes/novo'
    | '/representadas/novo'
    | '/clientes'
    | '/representadas'
    | '/clientes/$id/editar'
    | '/representadas/$id/editar'
    | '/clientes/$id'
    | '/representadas/$id'
  id:
    | '__root__'
    | '/'
    | '/clientes'
    | '/representadas'
    | '/transportadoras'
    | '/clientes/novo'
    | '/representadas/novo'
    | '/clientes/'
    | '/representadas/'
    | '/clientes/$id/editar'
    | '/representadas/$id/editar'
    | '/clientes/$id/'
    | '/representadas/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientesRoute: typeof ClientesRouteWithChildren
  RepresentadasRoute: typeof RepresentadasRouteWithChildren
  TransportadorasRoute: typeof TransportadorasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transportadoras': {
      id: '/transportadoras'
      path: '/transportadoras'
      fullPath: '/transportadoras'
      preLoaderRoute: typeof TransportadorasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/representadas': {
      id: '/representadas'
      path: '/representadas'
      fullPath: '/representadas'
      preLoaderRoute: typeof RepresentadasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/representadas/': {
      id: '/representadas/'
      path: '/'
      fullPath: '/representadas/'
      preLoaderRoute: typeof RepresentadasIndexRouteImport
      parentRoute: typeof RepresentadasRoute
    }
    '/clientes/': {
      id: '/clientes/'
      path: '/'
      fullPath: '/clientes/'
      preLoaderRoute: typeof ClientesIndexRouteImport
      parentRoute: typeof ClientesRoute
    }
    '/representadas/novo': {
      id: '/representadas/novo'
      path: '/novo'
      fullPath: '/representadas/novo'
      preLoaderRoute: typeof RepresentadasNovoRouteImport
      parentRoute: typeof RepresentadasRoute
    }
    '/clientes/novo': {
      id: '/clientes/novo'
      path: '/novo'
      fullPath: '/clientes/novo'
      preLoaderRoute: typeof ClientesNovoRouteImport
      parentRoute: typeof ClientesRoute
    }
    '/representadas/$id/': {
      id: '/representadas/$id/'
      path: '/$id'
      fullPath: '/representadas/$id/'
      preLoaderRoute: typeof RepresentadasIdIndexRouteImport
      parentRoute: typeof RepresentadasRoute
    }
    '/clientes/$id/': {
      id: '/clientes/$id/'
      path: '/$id'
      fullPath: '/clientes/$id/'
      preLoaderRoute: typeof ClientesIdIndexRouteImport
      parentRoute: typeof ClientesRoute
    }
    '/representadas/$id/editar': {
      id: '/representadas/$id/editar'
      path: '/$id/editar'
      fullPath: '/representadas/$id/editar'
      preLoaderRoute: typeof RepresentadasIdEditarRouteImport
      parentRoute: typeof RepresentadasRoute
    }
    '/clientes/$id/editar': {
      id: '/clientes/$id/editar'
      path: '/$id/editar'
      fullPath: '/clientes/$id/editar'
      preLoaderRoute: typeof ClientesIdEditarRouteImport
      parentRoute: typeof ClientesRoute
    }
  }
}

interface ClientesRouteChildren {
  ClientesNovoRoute: typeof ClientesNovoRoute
  ClientesIndexRoute: typeof ClientesIndexRoute
  ClientesIdEditarRoute: typeof ClientesIdEditarRoute
  ClientesIdIndexRoute: typeof ClientesIdIndexRoute
}

const ClientesRouteChildren: ClientesRouteChildren = {
  ClientesNovoRoute: ClientesNovoRoute,
  ClientesIndexRoute: ClientesIndexRoute,
  ClientesIdEditarRoute: ClientesIdEditarRoute,
  ClientesIdIndexRoute: ClientesIdIndexRoute,
}

const ClientesRouteWithChildren = ClientesRoute._addFileChildren(
  ClientesRouteChildren,
)

interface RepresentadasRouteChildren {
  RepresentadasNovoRoute: typeof RepresentadasNovoRoute
  RepresentadasIndexRoute: typeof RepresentadasIndexRoute
  RepresentadasIdEditarRoute: typeof RepresentadasIdEditarRoute
  RepresentadasIdIndexRoute: typeof RepresentadasIdIndexRoute
}

const RepresentadasRouteChildren: RepresentadasRouteChildren = {
  RepresentadasNovoRoute: RepresentadasNovoRoute,
  RepresentadasIndexRoute: RepresentadasIndexRoute,
  RepresentadasIdEditarRoute: RepresentadasIdEditarRoute,
  RepresentadasIdIndexRoute: RepresentadasIdIndexRoute,
}

const RepresentadasRouteWithChildren = RepresentadasRoute._addFileChildren(
  RepresentadasRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientesRoute: ClientesRouteWithChildren,
  RepresentadasRoute: RepresentadasRouteWithChildren,
  TransportadorasRoute: TransportadorasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
