/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientesIndexRouteImport } from './routes/clientes.index'
import { Route as ClientesNovoRouteImport } from './routes/clientes.novo'
import { Route as ClientesIdVisualizarRouteImport } from './routes/clientes.$id.visualizar'
import { Route as ClientesIdEditarRouteImport } from './routes/clientes.$id.editar'

const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesIndexRoute = ClientesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientesRoute,
} as any)
const ClientesNovoRoute = ClientesNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => ClientesRoute,
} as any)
const ClientesIdVisualizarRoute = ClientesIdVisualizarRouteImport.update({
  id: '/$id/visualizar',
  path: '/$id/visualizar',
  getParentRoute: () => ClientesRoute,
} as any)
const ClientesIdEditarRoute = ClientesIdEditarRouteImport.update({
  id: '/$id/editar',
  path: '/$id/editar',
  getParentRoute: () => ClientesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRouteWithChildren
  '/clientes/novo': typeof ClientesNovoRoute
  '/clientes/': typeof ClientesIndexRoute
  '/clientes/$id/editar': typeof ClientesIdEditarRoute
  '/clientes/$id/visualizar': typeof ClientesIdVisualizarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clientes/novo': typeof ClientesNovoRoute
  '/clientes': typeof ClientesIndexRoute
  '/clientes/$id/editar': typeof ClientesIdEditarRoute
  '/clientes/$id/visualizar': typeof ClientesIdVisualizarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRouteWithChildren
  '/clientes/novo': typeof ClientesNovoRoute
  '/clientes/': typeof ClientesIndexRoute
  '/clientes/$id/editar': typeof ClientesIdEditarRoute
  '/clientes/$id/visualizar': typeof ClientesIdVisualizarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clientes'
    | '/clientes/novo'
    | '/clientes/'
    | '/clientes/$id/editar'
    | '/clientes/$id/visualizar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clientes/novo'
    | '/clientes'
    | '/clientes/$id/editar'
    | '/clientes/$id/visualizar'
  id:
    | '__root__'
    | '/'
    | '/clientes'
    | '/clientes/novo'
    | '/clientes/'
    | '/clientes/$id/editar'
    | '/clientes/$id/visualizar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientesRoute: typeof ClientesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/': {
      id: '/clientes/'
      path: '/'
      fullPath: '/clientes/'
      preLoaderRoute: typeof ClientesIndexRouteImport
      parentRoute: typeof ClientesRoute
    }
    '/clientes/novo': {
      id: '/clientes/novo'
      path: '/novo'
      fullPath: '/clientes/novo'
      preLoaderRoute: typeof ClientesNovoRouteImport
      parentRoute: typeof ClientesRoute
    }
    '/clientes/$id/visualizar': {
      id: '/clientes/$id/visualizar'
      path: '/$id/visualizar'
      fullPath: '/clientes/$id/visualizar'
      preLoaderRoute: typeof ClientesIdVisualizarRouteImport
      parentRoute: typeof ClientesRoute
    }
    '/clientes/$id/editar': {
      id: '/clientes/$id/editar'
      path: '/$id/editar'
      fullPath: '/clientes/$id/editar'
      preLoaderRoute: typeof ClientesIdEditarRouteImport
      parentRoute: typeof ClientesRoute
    }
  }
}

interface ClientesRouteChildren {
  ClientesNovoRoute: typeof ClientesNovoRoute
  ClientesIndexRoute: typeof ClientesIndexRoute
  ClientesIdEditarRoute: typeof ClientesIdEditarRoute
  ClientesIdVisualizarRoute: typeof ClientesIdVisualizarRoute
}

const ClientesRouteChildren: ClientesRouteChildren = {
  ClientesNovoRoute: ClientesNovoRoute,
  ClientesIndexRoute: ClientesIndexRoute,
  ClientesIdEditarRoute: ClientesIdEditarRoute,
  ClientesIdVisualizarRoute: ClientesIdVisualizarRoute,
}

const ClientesRouteWithChildren = ClientesRoute._addFileChildren(
  ClientesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientesRoute: ClientesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
